[functions]
  node_bundler = "esbuild"
  # Only keep truly heavy native modules external.
  external_node_modules = ["@sparticuz/chromium", "puppeteer-core"]

# Run every 15 minutes (UTC)
[[scheduled.functions]]
  name = "techtasks-scheduler"
  cron = "*/15 * * * *"