[build]
  command = ""                    # no frontend build needed
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium", "puppeteer-core"]

[[scheduled.functions]]
  name = "techtasks-scheduler"
  cron = "*/15 * * * *"          # every 15 minutes (UTC)